apiVersion: v1
kind: Pod
metadata:
  name: file-writer
spec:
    containers:
    - name: file-writer
      image: rivianmfg/rivian-mfg-file-writer:latest
      volumeMounts: 
        - mountPath: /var/file-writer/
          name: file-writer-volume
    - name: s3upload
      image: s3-uploader:latest
      volumeMounts: 
        - mountPath: /var/file-writer/data/
          name: file-writer-volume
    volumes:
    - name: file-writer-volume