# A trivial file-writer app deployment spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-writer
  labels:
    app: file-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-writer
  template:
    metadata:
      labels:
        app: file-writer
    spec:
      containers:
      - name: file-writer
        image: rivianmfg/rivian-mfg-file-writer:latest
      # start s3-uploader to sync the files to the bucket specified
      - name: s3upload
        image: s3-uploader:latest
        imagePullPolicy: Never